// COD3R/course-vue-cod3r/calculator/src/main/Calculator.vue
<template>
  <div class="calculator">
      <Display value="1000"/>
      <Button label="AC" triple @onCalcButtonClick="clearMemory"/>
      <Button label="/" operation @onCalcButtonClick="SetOperation"/>
      <Button label="7" @onCalcButtonClick="addDigit"/>
      <Button label="8" @onCalcButtonClick="addDigit"/>
      <Button label="9" @onCalcButtonClick="addDigit"/>
      <Button label="*" operation @onCalcButtonClick="SetOperation"/>
      <Button label="4" @onCalcButtonClick="addDigit"/>
      <Button label="5" @onCalcButtonClick="addDigit"/>
      <Button label="6" @onCalcButtonClick="addDigit"/>
      <Button label="-" operation @onCalcButtonClick="SetOperation"/>
      <Button label="1" @onCalcButtonClick="addDigit"/>
      <Button label="2" @onCalcButtonClick="addDigit"/>
      <Button label="3" @onCalcButtonClick="addDigit"/>
      <Button label="+" operation @onCalcButtonClick="SetOperation"/>
      <Button label="0" double @onCalcButtonClick="addDigit"/>
      <Button label="." @onCalcButtonClick="addDigit"/>
      <Button label="=" operation @onCalcButtonClick="SetOperation"/>
  </div>
</template>

<script>

import Button from '../components/Button'
import Display from '../components/Display'

export default {
    components: {Display, Button},
    methods: {
        clearMemory(){

        },
        setOperation(operation){

        },
        addDigit(n){

        }
    }
}
</script>

<style>
    .calculator{
        height: 320px;
        width: 235px;
        border-radius: 5px;
        overflow: hidden;

        display: grid;
        grid-template-columns: repeat(4, 25%);
        grid-template-rows: 1fr 48px 48px 48px 48px 48px
    }
</style>

// COD3R/course-react-cod3r/calculadorav2/src/main/Calculator.jsx
import React, { Component } from 'react'
import './Calculator.css'
import Button from '../components/Button'
import Display from '../components/Display'

const initialState = {
  displayValue: '0',
  clearDisplay: false,
  operation: null,
  values: [0, 0],
  current: 0
}
export default class Calculator extends Component{
  state = { ...initialState }
  constructor(props) {
    super(props)
    this.clearMemory = this.clearMemory.bind(this)
    this.setOperation = this.setOperation.bind(this)
    this.addDigit = this.addDigit.bind(this)
  }
  clearMemory() {
    this.setState({ ...initialState })
  }

  setOperation(operation) {
    if(this.state.current === 0) {
      this.setState({
        operation,
        current: 1,
        clearDisplay: true
      })
    } else {
      const equals = operation === '='
      const currentOperation = this.state.operation
      const values = [...this.state.values]
      try {
        values[0] = eval(`${values[0]} ${currentOperation} ${values[1]}`)
      }
      catch {
        values[0] = this.state.values[0]
      }
      values[1] = 0
      this.setState({
        displayValue: values[0],
        operation: equals ? null : operation,
        current: equals ? 0 : 1,
        clearDisplay: !equals,
        values

      })
    }
  }

  addDigit(n) {
    if( n === '.' && this.state.displayValue.includes('.')){
      return 
    }
    const clearDisplay = this.state.displayValue === '0'
      || this.state.clearDisplay

    const currentValue = clearDisplay ? '' : this.state.displayValue
    const displayValue = currentValue + n
    this.setState({displayValue, clearDisplay: false})
    if ( n !== '.' ) {
      const i = this.state.current
      const newValue = parseFloat(displayValue)
      const values = [this.state.values]
      values[i] = newValue
      this.setState({ values })
    }
  }

  render() {
    return (
      <div className="calculator">
        <Display value={this.state.displayValue}/>
        <Button label="AC" triple click={this.clearMemory} />
        <Button label="/" operation click={this.setOperation} />
        <Button label="7" click={this.addDigit}/>
        <Button label="8"  click={this.addDigit} />
        <Button label="9"  click={this.addDigit} />
        <Button label="*" operation  click={this.setOperation} />
        <Button label="4"  click={this.addDigit} />
        <Button label="5"  click={this.addDigit} />
        <Button label="6"  click={this.addDigit} />
        <Button label="-"operation  click={this.setOperation} />
        <Button label="1"  click={this.addDigit} />
        <Button label="2"  click={this.addDigit} />
        <Button label="3"  click={this.addDigit} />
        <Button label="+" operation click={this.setOperation} />
        <Button label="0" double  click={this.addDigit} />
        <Button label="."  click={this.addDigit} />
        <Button label="=" operation click={this.setOperation} />
      </div>
    )
  }
}
