// COD3R/course-vue-cod3r/rotas-exercicios/src/components/template/Menu.vue
<template>
  <nav class="menu">
      <ul>
        <router-link to="/" tag="li" active-class="active" exact><a>Início</a></router-link>
        <router-link to="/usuario" tag="li" active-class="active"><a>Usuário</a></router-link>
      </ul>  
  </nav>
</template>

<script>
export default {

}
</script>

<style>

</style>

// COD3R/course-react-cod3r/Modulo-routes/navigation/src/components/layout/Menu.jsx
import React from 'react'
import './Menu.css'
import {Link} from 'react-router-dom'
const Menu = props => (
  <aside className="Menu">
    <nav>
      <ul>
        <li>
          <Link to="/about">Sobre</Link>
        </li>
        <li>
          <Link to="/param/123">Param #01</Link>
        </li>
        <li>
          <Link to="/naoExiste">Não Existe</Link>
        </li>
        <li>
          <Link to="/param/perereca">Param #02</Link>
        </li>
        <li>
          <Link to="/">Início</Link>
        </li>
      </ul>
    </nav>
  </aside>
)

export default Menu
